MODEL:
  # backbone part.
  BACKBONE:
    FREEZE_AT: 0
    NAME: "custom_bn_build_resnet_backbone" # we customize the momentum and eps in syncbn, to align with tf implementation.
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [127.5, 127.5, 127.5]
  PIXEL_STD: [127.5, 127.5, 127.5]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  
  # kmax part.
  META_ARCHITECTURE: "Compositor"
  SEM_SEG_HEAD:
    NAME: "CompositorHead"
    IGNORE_VALUE: 255
    NUM_PART_CLASSES: 41
    NUM_OBJECT_CLASSES: 159

  COMPOSITOR:
    PART_CLASS_WEIGHT: 6.0
    PART_DICE_WEIGHT: 6.0
    PART_MASK_WEIGHT: 0.6
    PART_INSDIS_WEIGHT: 2.0
    OBJECT_CLASS_WEIGHT: 3.0
    OBJECT_DICE_WEIGHT: 3.0
    OBJECT_MASK_WEIGHT: 0.3
    OBJECT_INSDIS_WEIGHT: 1.0

    PIXEL_INSDIS_TEMPERATURE: 0.6
    PIXEL_INSDIS_SAMPLE_K: 4096

    TRANS_DEC:
      NAME: "CompositorTransformerDecoder"
      DEC_LAYERS: [2, 2, 2]
      NUM_PART_QUERIES: 30
      NUM_OBJECT_QUERIES: 5
      IN_CHANNELS: [2048, 1024, 512, 256] # [512 * 4, 256 * 4, 128 * 4], the last dim is for final prediction
      DROP_PATH_PROB: 0.2
DATASETS:
  TRAIN: ("partimagenet_train",)
  TEST: ("partimagenet_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0005
  LR_SCHEDULER_NAME: "TF2WarmupPolyLR"
  MAX_ITER: 40000
  WARMUP_ITERS: 4000
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: False
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: [513, 513]
  MIN_SCALE: 0.5
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "compositor_semantic"
  MIN_SIZE_TEST: 513
  MAX_SIZE_TEST: 513
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2